### ISSUE TITLE
UI Enhancement: Implement New Theme for EduElites Website

### ISSUE THREAD

**Issue by Anikesh02** [Anikesh02/AL-frontend#2]
# UI Enhancement: Implement New Theme for EduElites Website

## Description
To refresh the look and feel of the EduElites platform, we need to implement a new theme across the entire website. This theme change should modernize our visual identity, improve user engagement, and ensure consistency across all pages and components.

## Objectives
- Update the visual design of the EduElites platform
- Improve user engagement through a more appealing interface
- Ensure consistency across all pages and components
- Maintain or improve current accessibility standards

## Tasks
1. [ ] Create a new colour palette that aligns with EduElites' brand identity
2. [ ] Design new UI components (buttons, forms, cards, etc.) that fit the new theme
3. [ ] Update the CSS files to reflect the new theme
4. [ ] Redesign the main layout structure if necessary
5. [ ] Update icons and graphical elements to match the new style
6. [ ] Ensure the new theme is responsive and works well on all device sizes
7. [ ] Implement a dark mode option
8. [ ] Update any theme-specific images or illustrations
9. [ ] Ensure all interactive elements have appropriate hover and focus states
10. [ ] Test the new theme across different browsers and devices

## Acceptance Criteria
- [ ] All pages consistently reflect the new theme
- [ ] Color contrast ratios meet accessibility standards
- [ ] The website maintains its performance metrics (load time, responsiveness) with the new theme
- [ ] User feedback is positive, with at least 80% of test users preferring the new theme
- [ ] The theme is easily customizable for potential white-labeling in the future

**Comment by 53gf4u1t** [comment]
Hi! Are you still working on this project? I'd like to help!

**Comment by Anikesh02** [comment]
> Hi! Are you still working on this project? I'd like to help!

Go ahead!

**Comment by 53gf4u1t** [comment]
<img width="465" alt="image" src="https://github.com/user-attachments/assets/5c8cd68f-fd6c-43e0-9a35-714ed02176b1">

@Anikesh02 I came up with this design for the homepage, any suggestions? If it's fine then I'll go for the implementation.

**Comment by Anikesh02** [comment]
> @Anikesh02 I came up with this design for the homepage, any suggestions? If it's fine then I'll go for the implementation.

It looks Great !! You can go ahead with the implementation.

**Comment by chinmayeebidaye** [comment]
I would like to work on this!

**Comment by Anikesh02** [comment]
> I would like to work on this!

@chinmayeebidaye Assigned
